/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxRunningRainbow: typeof import('./src/components/animation/BoxRunningRainbow.vue')['default']
    Index: typeof import('./src/components/content/Index.vue')['default']
    TrailingDots: typeof import('./src/components/animation/TrailingDots.vue')['default']
  }
}
